Refactor : Activity 리팩토링
metoring/walkerholic pull request #1
Opened 2021-12-13 07:32 UTC by yunhalee05

Activity 기능과 관련된 항목을 리팩토링 진행하였습니다.

ActivityService에 saveActivity로 단일화 되었던 메소드는 updateActivity, createActivity로 분리하여 역할을 분명하게 하고, setter를 이용한 값변경을 activity 엔티티내의 updateActivity 비지니스 로직을 이용한 변경으로 바꾸어 메소드의 목적을 알 수 있게 하였습니다.

ActivityCreateDTO에서는 toActivity함수를 만들어 Activity생성자를 이용하여 정보를 포함한 새로운 activity를 반환할 수 있도록 하였습니다.

2021-12-14 13:28 UTC, brainbackdoor requested changes
첫번째 PR을 빠르게 보냈네요! ㅎㅎ
제가 주중이나 주말이나 이래저래 바빠서 피드백이 좀 늦을 수는 있지만 최대한 24시간 내로 해보려고 노력할게요~
몇가지 피드백을 남겨두었는데요. 이해가 잘 안되는게 있다면 Comment 부탁해요~🙏🏻
오늘 하루도 고생 많으셨어요 ~

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +    @PostMapping("/activity/save")
RESTful API 에 익숙하다면 save path 가 없어도 activity를 생성함을 알 수 있지 않을까요
> https://brainbackdoor.tistory.com/53

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/domain/Activity.java
> +    public Activity updateActivity( Activity requestActivity) {
```suggestion
    public Activity updateActivity(Activity requestActivity) {
```
google java style guide가 익숙치 않다면, IntelliJ 또는 Eclipse의 formatting 기능을 활용해보세요.
> https://google.github.io/styleguide/javaguide.html

IntelliJ 단축키는  Ctrl+Alt+L(윈도우), Cmd+Alt+L(맥)
Eclipse 단축키는 Ctrl+Shift+F(윈도우), Cmd+Shift+F(맥)

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/dto/ActivityCreateDTO.java
> +    }
dto 에서 entity를 의존하도록 구성하셨군요! 잘하셨어요~
entity에서는 dto를 알지 못하도록 하는 것이 좋지요.

이와 별개로 assembler pattern이란 것도 있으니 한번 참고해보세요
>  http://redutan.github.io/2016/04/15/poeaa-distribution-pattern

추가적으로 아래 링크들에서 DTO 관련 논의들이 있으니 참고해보세요.
https://www.slipp.net/questions/22
https://www.slipp.net/questions/23
https://www.slipp.net/questions/93

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        MultipartFile multipartFile) {
개행의 기준은 혹시 어떻게 세우고 계실까요?

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(activity);
create activity 인데 image도 함께 저장하고 있군요!
그런데 `activityRepository.save(activity);`를 두번 호출하는 이유가 있나요?

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .get();
Optional 에 대해서 바로 get하기 보단 없는 경우에 대한 예외를 처리해주는건 어떨까요

> http://homoefficio.github.io/2019/10/03/Java-Optional-바르게-쓰기/

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        saveActivityImage(updatedActivity, multipartFile, false);
마지막 인자의  true와 false는 어떤 의미인지 이 코드만 봐서는 알 수가 없겠네요

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        return new ActivityCreateDTO(existingActivity);
요청과 응답의 정보가 같나요? 같은 DTO를 쓰는군요. 혹시 사용하지 않는 정보는 없나요?

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        return new ActivityCreateDTO(existingActivity);
save 후 영속화된 객체에는 id 값이 있을텐데 이를 반환하지는 않나요?

2021-12-14 13:28 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +
이 부분이 ActivityService의 관심사일까요? 파일 이름, 위치 등의 책임을 담당하는 객체를 도출하는 것은 어떨까요

2021-12-15 10:02 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +        return id != null ? activityService.updateActivity(activityCreateDTO, multipartFile)
보내주신 RESTful API 글을 읽고 자원과 그 행위를 나타내기 위해서 POST와 PUT으로 구분하여 create, update를 나타내는 방법으로 수정하였습니다!

2021-12-15 10:05 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +    @PostMapping("/activity/save")
게시글을 확인하여 api를 수정하였습니다!

2021-12-15 10:05 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/domain/Activity.java
> +    public Activity updateActivity( Activity requestActivity) {
확인하여 수정하였습니다!

2021-12-15 10:05 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/dto/ActivityCreateDTO.java
> +    }
확인하였습니다! 😁

2021-12-15 10:07 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        MultipartFile multipartFile) {
자바 코드 컨벤션에 따라서 한줄에 80자가 넘어가면 , 뒤에서 행을 바꾸고 있습니다!

2021-12-15 10:08 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(activity);
이미지를 저장하는 Url을 activityUploads/ + activity의 id + / 파일이름 으로 설정하기 위해서 새로 생성되는 activity의 아이디를 얻기 위해서 save를 먼저 해주었습니다!

2021-12-15 10:09 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .get();
ActivityNotFound 예외를 만들고 .orElseThrow를 사용하여 예외를 던지도록 수정하였습니다!

2021-12-15 10:10 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        saveActivityImage(updatedActivity, multipartFile, false);
isCreated boolean 값을 설정하여 의미를 알 수 있도록 수정하였습니다!

2021-12-15 10:11 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        return new ActivityCreateDTO(existingActivity);
imageUrl, id 정보가 해당되지 않음을 확인하여 ActivityRequest, ActivityReponse 로 나누어 해당 정보를 담도록 수정하였습니다!

2021-12-15 10:38 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        }
이 부분을 확인하고 activity는 생성될 시에 이미지 부분이 필수 값으로 설정되지 않았기때문에(등록하지 않아도 되도록 설정하였습니다!) bean validation이 아닌 AmazonS3Util에 isEmpty메소드를 생성하여 saveImage메소드에서 해당파일이 추가되었는지 확인하고 이미지를 등록하지 않았을 경우(null) 저장을 생략하는 방법으로 수정하였습니다! 그런데 혹시 필수값이 아닌 경우에는 이러한 방법을 사용해도 괜찮은지 아니면 if 구문을 생성하고 saveImage 메소드 파라미터에 bean validation을 넣어야 하는지 궁금합니다!😀

2021-12-15 10:39 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +
해당 부분을 확인하고 이미지 정해진 디렉토리에 파일을 저장하는 메소드는 AmazonS3Util로 이동하고 saveActivityImage는 디렉토리명을 사용하여 해당 메소드를 부르는 방식으로 수정하였습니다!

2021-12-15 13:57 UTC, woowahanCU commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(activity);
activity 와 저 file은 라이프사이클이 같나요?
가령, 생성될 때 이미지가 반드시 존재하여야 하며 activity를 제거하면 이미지도 제거되나요?
activity를 생성하는 로직에서 update 까지 발생하는 이유가 무엇일까요?

2021-12-15 14:00 UTC, woowahanCU commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        }
https://github.com/metoring/walkerholic/pull/1#discussion_r769649374
와 같은 논의인데요.
이미지 업로드가 필수인 경우와 아닌 경우가 있는걸까요?
activity를 생성하고 이미지 업로드는 별개로 요청하는 것은 어떨까요?

2021-12-15 14:05 UTC, woowahanCU commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +
음.. 우선 반드시 util을 작성해야 한다면, private 생성자를 가지도록 구현해보세요.

> https://slipp.net/questions/360

참고로 저는 util 클래스는 객체지향적인 설계에 좋지 않은 영향을 주기 때문에 가급적 지양하고 있습니다.

> https://unabated.tistory.com/m/entry/왜-자바에서-static의-사용을-지양해야-하는가
> https://stackoverflow.com/questions/4002201/why-arent-static-methods-considered-good-oo-practice

2021-12-15 15:04 UTC, brainbackdoor requested changes
피드백 반영 잘 해주셨네요~
몇가지 피드백 추가로 남겨두었어요. 
오늘 하루도 고생 많으셨어요~ 🙇🏻‍♂️

2021-12-15 15:04 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        ActivityResponse activityResponse1 = activityService
변수에 숫자를 넣는건 지양해주세요. 
연속적인 숫자를 덧붙인 이름(a1, a2, ..., aN) 덧붙이거나 불용어(Info, Data, a, an, the)를 추가하는 방식은 적절하지 못합니다.
이름이 달라야 한다면 의미도 달라져야 합니다.

2021-12-15 15:04 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +            .contains(AWS_S3_BUCKET_URL + "activityUploads/" + activityResponse1.getId() + "/"));
```suggestion
            .contains(bucketUrl + "activityUploads/" + activityResponse1.getId() + "/"));
```

상수가 맞나요? 
그리고 상수 값은 static final이 관례입니다.

> https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2021-12-17 11:18 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(activity);
activity와 activityImage는 라이프사이클이 동일해야(activity가 생성될 때 이미지도 생성되고 activity가 제거될 때 이미지도 제거되어야 한다)만 한다고 판단하여 create메소드 실행시 multipartFile이 넘어오지 않는다면 baseImageUrl을 properties에서 @Value로 가져와서 등록하도록 변경하였습니다! 
그런데 이 부분은 이미지 Url 설정시  activityUploads/ + activity의 id + / 파일이름으로 설정하기 위해서(id 값이 필요해서) save를 먼저 해주고 imageUrl을 update해야하는 상황이 계속해서 발생하는데 혹시 이부분을 어떻게 하면 update까지 발생하지 않도록 설정할 수 가 있을까요? 
activity 와 이미지 업로드 별개로 하는 방법도 생각해 보았지만 id를 활용해 imageUrl을 구성하고 activity의 속성인 imageUrl을 변경하기 위해서는 결국 activity update가 발생하고 있습니다 😭

2021-12-17 11:19 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        }
이미지 업로드에 새로운 이미지를 등록하고자 하지 않는 경우 기본 이미지 url을 리턴하도록 s3ImageUploader를 수정하였습니다!

2021-12-17 11:22 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +
해당 블로그 글을 읽고 s3이미지 업로드 부분을 static 메소드를 갖지 않는 s3ImageUploader로 구현하여 @Component로 등록하여 사용할 수 있도록 수정하였습니다! 
s3ImageUploader 파일은 common/service폴더 안에 위치하도록 이동하였습니다!

2021-12-17 11:51 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +        return activityService.getActivity(id);
엘레강스 오브젝트 메서드 이름 선택 부분을 보고 객체를 존중하는 방법이란 생각이 들어 get 동사를 제외한 activity, activities의 이름으로 메서드 명을 바꾸었습니다!

그런데 객체의 속성을 변경시키는 메서드가 리턴 값을 지니고 있을 때에는 (조정자 + 빌더) N개의 목적성을 갖고 있어 메서드 분리가 필요하다는 부분을 보았습니다. 여기서 create, update메서드가 해당하는데 create메소드와 값을 생성된 값을 리턴하는 메서드를 따로 분리하는 것도 필요한 부분인지 궁금합니다! 메서드를 분리하면 controller에서 create메소드와 값을 리턴한는 메소드 두가지를 불러야 하는 것일까요? 😀

2021-12-17 11:51 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +    @DeleteMapping("/activity/{id}")
확인하여 수정하였습니다!

2021-12-17 11:51 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/exception/ActivityNotFoundException.java
> +public class ActivityNotFoundException extends RuntimeException{
수정완료하였습니다!

2021-12-17 11:52 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +    private final AmazonS3Utils amazonS3Utils;
해당 내용을 확인하여 생성자 주입을 통하도록 변경하였습니다!

2021-12-17 11:54 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .orElseThrow(() -> new ActivityNotFoundException(
GlobalExceptionHandler에서 CustomException으로 잡히지 않은 RuntimeError는 404 코드를, ExceptionError는 500코드를 반환하도록 설정하고 ExceptionHandler를 통하여 CustomException(ActivityNotFoundException)는 처리하도록 변경하였습니다!

2021-12-17 12:00 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(updatedActivity);
JPA의 변경감지를 사용하도록 해당부분을 변경하였습니다!

transaction관리는 프레젠테이션계층과 비지니스로직 사이에서 시작되고 종료되어야 한다고 판단하여 service 레이어에서 Transaction이 적용되도록 변경하였습니다!

2021-12-17 12:00 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        return activityResponses;
Stream API, Method Reference 를 적용하도록 변경하였습니다!

2021-12-17 12:02 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        String dir = "activityUploads/" + id;
"activityUploads/"를 UPLOAD_DIR 상수로 변경하여 적용하였습니다!

2021-12-17 12:05 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/util/AmazonS3Utils.java
> +            return uploadFile(uploadDir, multipartFile);
이미 이미지 파일이 존재하는 경우(activity 를 업데이트 하는 경우) 해당 폴더를 비우고 파일을 업로드 하기 위해서 isCreated 변수를 필요로 하였으나 해당 부분을 s3ImageUpload에서 removeFolder메소드를 통해 구현하여 불필요한 isCreated변수를 제거하도록 변경하였습니다!

2021-12-17 12:05 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        ActivityResponse activityResponse1 = activityService
확인하여 변수명을 변경하였습니다!

2021-12-17 12:08 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +            .contains(AWS_S3_BUCKET_URL + "activityUploads/" + activityResponse1.getId() + "/"));
AWS_S3_BUCKET_URL은 value애노테이션을 통하여 properties에 작성된 값을 불러오도록 설정하였습니다!

혹시 value애노테이션으로 불러온 값도 final 설정이 필요할까요? 😀

🙌 감사합니다!! 🙌

2021-12-17 12:14 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +        return activityService.deleteActivity(id);
확인하여 수정하였습니다!

2021-12-18 16:58 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(activity);
1. 라이프사이클이 같다면, null인 경우는 예외처리를 해야 하지 않나요? baseImageUrl와 관련된 로직은 어디서 확인할 수 있나요?
2. 이미지 파일의 null 체크는 Service Layer 까지 내려와서 확인하는 것이 아니라, 요청 값에 대한 유효성 검증 차원에서 Controller 에서 확인하는 것은 어떨까요? 
2. image url에 반드시 activity id 가 필요한지도 의문입니다. image url에도 depth가 필요한가요? id를 알면 activity 를 알 수 있고 그럼 url을 'activityUploads/파일이름'으로 구성해두 알 수 있지 않나요?
3. url 디자인은 kebab case로 하는건 어떨까요?
4. 현재도 update가 발생하고 있는데, 업로드를 별개로 요청할 시에 요청을 두번 하는 것 외에 다른 이슈가 있을까요?

2021-12-18 17:03 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +        return activityService.getActivity(id);
타인의 의견을 맹목적으로 따를 필요는 없다고 생각해요. 그에 대한 윤하님 나름대로의 논리만 타당하면 된다고 생각해요. 
가령, JPA 에서도 create 시에 entity 를 반환하는데요. 저자는 이런 부분도 비판하고 있어요.
적절히 수용할 것만 수용하면 됩니다 😬

2021-12-18 17:07 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .orElseThrow(() -> new ActivityNotFoundException(
1. (ExceptionHandler로 정의하지 않은) 모든 RuntimeException이 존재하지 않는 리소스를 의미하는 404로 정의하신 이유가 있으실까요?
2. ActivityNotFoundException 과 같이 도메인별 not found exception을 모두 ExceptionHandler로 잡다보면 중복코드가 많이 발생하지 않을까요?

2021-12-18 17:10 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(updatedActivity);
Service Layer의 특징이 하나 생겼군요!
- 트랜잭션을 관리한다.

2021-12-18 17:16 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +            .contains(AWS_S3_BUCKET_URL + "activityUploads/" + activityResponse1.getId() + "/"));
properties에서 불러온 값을 변경할 일이 있을까요? 가변데이터로 관리하지 않기 위해 properties 로 관리한다고 생각해요.
그런 의미에서 final은 필요하다고 생각해요. 
그리고 위의 피드백은 상수가 아닌데, 대문자 + snake case 라 피드백 드린 거였어요.

2021-12-18 17:36 UTC, brainbackdoor requested changes
피드백 반영 잘 해주셨네요! 👏🏻
몇가지 질문드린 부분에 대해 답변 주시면 머지할게요~

2021-12-18 17:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +        @RequestParam("description") String description,
```suggestion
        @RequestBody ActivityRequest activityRequest
```
description과 같은 데이터를 굳이 request parameter로 받는 이유가 있으실까요?

2021-12-18 17:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +@Transactional(readOnly = true)
```suggestion
@Transactional
```
readOnly 인 부분에서만 옵션을 추가하는 것은 어떨까요?

2021-12-18 17:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .collect(Collectors.toList());
```suggestion
    public List<ActivityResponse> activities() {
        return activityRepository.findAll().stream()
            .map(ActivityResponse::new)
            .collect(Collectors.toList());
```
의미있는 단위로 개행하는 것은 어떨까요

2021-12-18 17:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .saveImageByFolder(uploadDir, multipartFile);
```suggestion
    private void uploadImage(Activity activity, MultipartFile multipartFile)
        throws IOException {
        String uploadDir = UPLOAD_DIR + activity.getId();
        String imageUrl = s3ImageUploader
            .uploadImageByFolder(uploadDir, multipartFile);
```
용어를 통일하는 것은 어떨까요

2021-12-18 17:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/common/exception/GlobalExceptionHandler.java
> +        HttpStatus status = HttpStatus.BAD_REQUEST;
400 status code를 반환하는군요?

2021-12-18 17:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/common/service/S3ImageUploader.java
> +            return uploadFile(uploadDir, multipartFile);
파일 하나 올리기 위해 해당 디렉토리를 지우는군요!

2021-12-18 17:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +    @PostMapping("/activities")
공통 depth는 `@RequestMapping("/activities")`을 활용할 수 있지 않을까요

2021-12-20 15:18 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(activity);
라이프 사이클을 같게 하기 위해서 이미지 업로드 기능을 uploadImage로 따로 빼내었습니다!
activity create시에 만약 imageUrl이 존재하지 않는다면 baseImageUrl을 설정하도록 activity.setDefaultImageUrl을 이용하여 기본 이미지 url로 저장하도록 하였습니다. 
Controller에서 uploadImage 메서드를 실행할 때 RequestParam의 기본값인 required=true를 이용하여 null체크를 하도록 변경하였습니다. 
activity는 하나의 이미지를 가지고 있기 때문에 아이디가 필요하지 않다고 판단하여 이미지 저장시 activity-uploads/파일이름 (kebab case) 의 형태로 저장하도록 변경하였습니다!
이미지 url을 반환하는 이미지 저장메서드를 따로 빼내어 주고 id값을 url에 넣지 않도록 변경하여 activity를 create할 때에 update로직이 추가로 발생하지 않도록 변경하였습니다!

2021-12-20 15:18 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +        return activityService.getActivity(id);
확인하였습니다 !😃

2021-12-20 15:25 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .orElseThrow(() -> new ActivityNotFoundException(
UncheckedException(RuntimeException)중 예상하지 못한 예외가 발생시 서버 쪽 잘못을 나타내는 INTERNAL_SERVER_ERROR로 표기하는 것이 옳다고 판단하여 해당 부분을 수정하였습니다!

도메인별 notFoundException이 불필요하게 ExceptionHandler에서 잡히지 않도록 하기 위하여 대표적으로 EntityNotFoundException, InvalidValueException, BadRequestException, AuthException을 만들고 이 커스텀 예외을  ExceptionHandler에서 처리하도록 하였습니다. 상세하게 발생하는 ActivityNotFoundException와 같은 예외 해당 속성에 맞는 예외(EntityNotFoundException)를 상속하여 중복코드가 ExceptionHandler에서 발생하지 않도록 변경하였습니다!

2021-12-20 15:26 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activityRepository.save(updatedActivity);
확인하였습니다!

2021-12-20 15:26 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +            .contains(AWS_S3_BUCKET_URL + "activityUploads/" + activityResponse1.getId() + "/"));
확인하여 변경하였습니다!

2021-12-20 15:27 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +        @RequestParam("description") String description,
해당 부분 확인하여 RequestBody로 변경하였습니다!

2021-12-20 15:27 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +@Transactional(readOnly = true)
전체적으로 @Transactional을 주고 해당부분만 readOnly옵션을 적용하도록 변경하였습니다!

2021-12-20 15:27 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .collect(Collectors.toList());
해당부분 확인하여 수정하였습니다!

2021-12-20 15:28 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +            .saveImageByFolder(uploadDir, multipartFile);
해당 부분 확인하여 변경하였습니다!

2021-12-20 15:30 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/common/exception/GlobalExceptionHandler.java
> +        HttpStatus status = HttpStatus.BAD_REQUEST;
해당부분 요청한 자원이 존재하지 않을 때 반환하는 NOT_FOUND (404)코드를 반환하도록 변경하였습니다!

2021-12-20 15:31 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/common/service/S3ImageUploader.java
> +            return uploadFile(uploadDir, multipartFile);
해당부분 imageUrl을 확인하여 파일을 삭제하도록 변경하였습니다!

2021-12-20 15:31 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
> +    @PostMapping("/activities")
해당 부분 확인하여 변경하였습니다!

감사합니다!!😀 🙌

2021-12-20 19:08 UTC, brainbackdoor approved these changes
몇가지 Comment 남겼어요~ 확인 부탁드려요~ ㅎㅎ
첫번째 PR 부터 제가 리뷰를 오래 끌었군요.. Conversation이 83개라니..
이 PR은 여기서 Approve 할게요. Comment는 확인해보시고 다음 PR에서 반영해주셔도 좋습니다.
고생 많으셨어요~ 💯

2021-12-20 19:08 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activity.setDefaultImageUrl(activityRequest.getImageUrl(), defaultImageUrl);
```suggestion
         Activity activity = activityRequest.toActivity(defaultImageUrl);
 ```

### * ActivityRequest
```java
    public Activity toActivity(String defaultImageUrl) {
        if (imageUrl == null || imageUrl.isEmpty() || imageUrl.isBlank()) {
            return new Activity(name, score, description, defaultImageUrl);
        }
        return toActivity();
    }

    public Activity toActivity() {
        return new Activity(name, score, description, imageUrl);
    }
```


activityRequest의 정보를 꺼내서 activity 내에서 비교할 필요가 있을까요?

---

그리고 defaultImageUrl 이 Activity 의 관심사인가도 한번 생각해볼 필요가 있을꺼 같아요.

만약 그렇다면 상수로 관리하는건 어떨까요

```java
    public Activity(String name, Integer score, String description, String imageUrl) {
        this.name = name;
        this.score = score;
        this.description = description;
        this.imageUrl = get(imageUrl);
    }

    private String get(String imageUrl) {
        if (imageUrl == null || imageUrl.isEmpty() || imageUrl.isBlank()) {
            return AWS_S3_BASE_IMAGE_URL;
        }
        return imageUrl;
    }
```

2021-12-20 19:08 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        System.out.println(existingActivity.getImageUrl().replaceAll(bucketUrl, ""));
표준출력보다는 logger를 사용하는 것은 어떨까요
로깅 프레임워크를 이용하면 파일을 쪼개는 정책을 설정할 수 있고, 여러 서버의 로그를 한곳에서 모아서 보는 시스템을 활용할 수도 있습니다.

https://beyondj2ee.wordpress.com/2012/11/09/logback-사용해야-하는-이유-reasons-to-prefer-logback-over-log4j/

2021-12-20 19:08 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        s3ImageUploader.deleteFile(existingActivity.getImageUrl().replaceAll(bucketUrl, ""));
추상화 수준이 다른데요. 조건절을 메서드로 추출하는건 어떨까요

2021-12-20 19:08 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        assertTrue(imageUrl.contains(fileName));
properties 가 없어서 테스트하기가 어렵네요 ㅎ;
코드만 보면 디렉토리와 파일명이 고정되어 있어서 테스트를 반복할 경우 실패할거 같은데요. 
이상 없나요?

2021-12-21 07:41 UTC, merged

2021-12-22 17:06 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/controller/ActivityController.java
>      }
해당부분 확인하여 별도로 이미지 업로드 경로가 없기에 activity를 생성하고 이미지파일이 존재하는 경우 Postmapping("/{id}/images")경로를 통하여 이미지 업로드 하도록 변경하였습니다!

2021-12-22 17:07 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        activity.setDefaultImageUrl(activityRequest.getImageUrl(), defaultImageUrl);
해당내용 확인하여 디폴트 이미지 설정을 create메서드에서 처리하도록 변경하여 적용하였습니다!

2021-12-22 17:07 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        System.out.println(existingActivity.getImageUrl().replaceAll(bucketUrl, ""));
확인하였습니다!😀

2021-12-22 17:07 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +        s3ImageUploader.deleteFile(existingActivity.getImageUrl().replaceAll(bucketUrl, ""));
해당부분 확인하여 디폴트 이미지 확인으로 변경하였습니다!

2021-12-22 17:07 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        assertTrue(imageUrl.contains(fileName));
이미지는 업로드 시에 System.currentTimeMillis()를 통하여 이미지 이름을 중복되는 것을 방지하여 저장하도록 하고 있어 테스트는 반복정으로 통과되었습니다!